<?php

namespace AppBundle\Repository;

/**
 * DonationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonationRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     * Get sum of donation bags
     */
    public function sumQuantityBags()
    {
        $query = $this->createQueryBuilder('d')
            ->select('sum(d.quantity)')
            ->getQuery()
            ->getSingleScalarResult();
        return $query;
    }

    public function institution()
    {
        $query = $this->createQueryBuilder('d')
            ->select('count(d.institution)')
            ->groupBy('d.institution')
            ->getQuery()
            ->getOneOrNullResult();
        return $query;
    }
}
