<?php

namespace AppBundle\Repository;

/**
 * DonationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonationRepository extends \Doctrine\ORM\EntityRepository
{
    public function sumQuantityBags()
    {
        $query = $this->createQueryBuilder('d')
            ->select('sum(d.quantity)')
            ->getQuery()
            ->getSingleScalarResult();
        return $query;
    }
}
