<?php

namespace AppBundle\Repository;

/**
 * GiftStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GiftStateRepository extends \Doctrine\ORM\EntityRepository
{
}
