# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: AppBundle:User
                property: email
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        secured_area:
            pattern: ^/
            logout: true
            http_basic: ~
            provider: our_db_provider
            anonymous: true
            logout_on_user_change: true
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path: /user/logged
            oauth:
                resource_owners:
                    facebook:           "/login/check-facebook"
                    google:             "/login/check-google"
                    twitter:             "/login/check-twitter"
                    fos_userbundle: "/login/check-custom"
#                    my_github:          "/login/check-github"
                login_path:        /login
                use_forward:       false
                failure_path:      /login
                check_path: /login_checks
                oauth_user_provider:
                    service: my.oauth_aware.user_provider.service
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false


    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }